# Use a imagem oficial do MySQL como base
FROM mysql:8.0

# Adiciona o arquivo .sql ao container
ADD https://raw.githubusercontent.com/gustavolendimuth/moodle-boilerplate/pazemente/i9791849_wfkz1.sql /docker-entrypoint-initdb.d/dump.sql